# Configuration for welcome - https://github.com/behaviorbot/welcome
# .github/config.yml

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ğŸ’– Thanks for opening this pull request! ğŸ’–
  A good commit message should describe what changed and why.
  We use [semantic commit messages](https://github.com/virgilwashere/mautic-cron-commands/blob/master/CONTRIBUTING.md#commit-message-guidelines) to streamline the release process. Before your pull request can be merged, you should **update your pull request title** to start with a semantic prefix.
  Examples of commit messages with semantic prefixes:
  - `docs: ğŸ“ address the upgrade process`
  - `feat: âœ¨ add command write:docs:forme`
  - `fix: ğŸ› lookup the correct parameter`
  You are encouraged to [include applicable emoji](https://github.com/virgilwashere/mautic-cron-commands/blob/master/CONTRIBUTING.md#emoji) in commit messages after the semantic prefix.
  # Things that will help get your PR across the finish line:
  # - Follow the JavaScript, C++, and Python [coding style](https://github.com/virgilwashere/mautic-cron-commands/blob/master/docs/coding-style.md).
  # - Run `npm run lint` locally to catch formatting errors earlier.
  # - Document any user-facing changes you've made following the [documentation styleguide](https://github.com/virgilwashere/mautic-cron-commands/blob/master/docs/styleguide.md).
  # - Include tests when adding/changing behavior.
  # - Include screenshots and animated GIFs whenever possible.
  # We get a lot of pull requests on this repo, so please be patient and we will get back to you as soon as we can.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request with us! ğŸ‰ğŸ‰ğŸ‰

# It is recommended to include as many gifs and emojis as possible!